spring.application.name=api-gateway
server.port=9090

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Automatic Gateway routing using Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator
management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=gateway,health

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem