
spring.application.name=cart-service
server.port=8081


#postgresql config
spring.datasource.url=jdbc:postgresql://localhost:5432/cart_service_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=thabith
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}


spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem